name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print time to console
        run: |
          date +"%Y-%m-%d"

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies and build with Maven
        run: mvn install -B -DskipTests

      - name: Run tests
        run: mvn test

      - name: Verify code coverage
        run: mvn verify
